const DEFAULT_45_ADVISORS = [
  // OSMANLI (15 Aday)
  { id:"adv_os_1", name:"KÃ¢tip Hamdi Efendi", role:"Defterhane Ã‡Ä±raÄŸÄ±", stars:1, salary:12000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"+%1 Vergi Geliri", debuff:"Bina yapÄ±mÄ± +%1 pahalÄ±.", taxBonus:1, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:-1, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:2, maxAge:15, yearsSinceUpgrade:0 },
  { id:"adv_os_2", name:"TopÃ§u KalfasÄ± Veli", role:"Tophane DÃ¶kÃ¼mcÃ¼sÃ¼", stars:1, salary:15000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"-%2 TopÃ§u BakÄ±mÄ±", debuff:"Ordu bakÄ±mÄ± +%1.", taxBonus:0, milUpkeepDiscount:-1, navyUpkeepDiscount:0, artUpkeepDiscount:2, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:3, maxAge:18, yearsSinceUpgrade:0 },
  { id:"adv_os_3", name:"DerviÅŸ Cemal", role:"Tekke DerviÅŸi", stars:1, salary:10000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"+1 Mutluluk", debuff:"ElveriÅŸli nÃ¼fus -200.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_os_4", name:"SubaÅŸÄ± BahadÄ±r AÄŸa", role:"AsayiÅŸ Zabiti", stars:2, salary:25000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"AnarÅŸistlerin zararÄ±nÄ± %25 azaltÄ±r.", debuff:"Mutluluk -1 puan.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:4, maxAge:20, yearsSinceUpgrade:0 },
  { id:"adv_os_5", name:"Reis Ä°lyas", role:"KadÄ±rga KaptanÄ±", stars:2, salary:30000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"-%3 Donanma BakÄ±mÄ±", debuff:"Ticaret -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:3, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:6, maxAge:25, yearsSinceUpgrade:0 },
  { id:"adv_os_6", name:"Mimar ÅÃ¼krÃ¼ Ã‡elebi", role:"Hassa MimarÄ±", stars:2, salary:28000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"-%3 Bina YapÄ±m Maliyeti", debuff:"YÄ±llÄ±k 3.000 TL ÅŸantiye masrafÄ±.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:3, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:24, yearsSinceUpgrade:0 },
  { id:"adv_os_7", name:"Defterdar Muhsin PaÅŸa", role:"SÄ±kÄ± Muhasebeci", stars:3, salary:50000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"+%4 Vergi Geliri", debuff:"Mutluluk -2 puan.", taxBonus:4, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:7, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_os_8", name:"Kurt Ali AÄŸa", role:"KÄ±ÅŸla AÄŸasÄ±", stars:3, salary:55000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"-%5 Asker SatÄ±n Alma Ä°ndirimi", debuff:"Piyade bakÄ±mÄ± +%2.", taxBonus:0, milUpkeepDiscount:-2, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:5, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:8, maxAge:26, yearsSinceUpgrade:0 },
  { id:"adv_os_9", name:"KuÅŸÃ§ubaÅŸÄ± Seyfi Efendi", role:"Divan Ä°stihbaratÃ§Ä±sÄ±", stars:3, salary:48000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"Casusluk YanÄ±lmasÄ±nÄ± %10'a dÃ¼ÅŸÃ¼rÃ¼r.", debuff:"Ä°stihbarat bÃ¼tÃ§esi Ã§eker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:true, ageYears:4, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_os_10", name:"Kaptan-Ä± Derya Turgut PaÅŸa", role:"Denizler Fatihi", stars:4, salary:85000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"-%6 Donanma BakÄ±mÄ± & -%4 Gemi AlÄ±mÄ±", debuff:"Ticaret geliri -%2.", taxBonus:-2, milUpkeepDiscount:0, navyUpkeepDiscount:6, artUpkeepDiscount:0, recruitDiscount:4, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:10, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_os_11", name:"DÃ¶kÃ¼mcÃ¼baÅŸÄ± Urbanzade", role:"BÃ¼yÃ¼k Åahi TopÃ§usu", stars:4, salary:90000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"-%7 TopÃ§u BakÄ±mÄ±", debuff:"Top alÄ±m fiyatÄ± +%3.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:7, recruitDiscount:-3, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:9, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_os_12", name:"MÃ¼derris Ebu FazÄ±l Efendi", role:"Ulema BaÅŸÄ±", stars:4, salary:75000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"+4 Mutluluk & -%3 Bina Ä°ndirimi", debuff:"Vergi toplama -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:3, happinessBonus:4, stopAnarchy:false, spyAccuracyBonus:false, ageYears:12, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_os_13", name:"Veziriazam Demir KÃ¶prÃ¼lÃ¼ PaÅŸa", role:"Mutlak Otorite", stars:5, salary:160000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"+%8 Vergi Geliri & Ä°syanÄ± %0 Yapar", debuff:"Mutluluk -3 puan.", taxBonus:8, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-3, stopAnarchy:true, spyAccuracyBonus:false, ageYears:14, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_os_14", name:"Serdar-Ä± Ekrem Zafer Sinan PaÅŸa", role:"Cihan KomutanÄ±", stars:5, salary:150000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"-%8 Ordu BakÄ±mÄ± & -%5 Sefer Ä°kmali", debuff:"YÄ±llÄ±k paÅŸa harcÄ±rahÄ± ister.", taxBonus:0, milUpkeepDiscount:8, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:5, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:11, maxAge:29, yearsSinceUpgrade:0 },
  { id:"adv_os_15", name:"Hazine NazÄ±rÄ± Karun Efendi", role:"Mali Deha", stars:5, salary:140000, targetName:"OsmanlÄ± Ä°mparatorluÄŸu", buff:"+%10 Vergi Geliri", debuff:"Komisyon keser.", taxBonus:10, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:13, maxAge:30, yearsSinceUpgrade:0 },

  // KIRIM HANLIÄI (15 Aday)
  { id:"adv_kr_1", name:"OtlakÃ§Ä± Timur AÄŸa", role:"BozkÄ±r Seyisi", stars:1, salary:10000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%2 SÃ¼vari/Ordu BakÄ±mÄ±", debuff:"Bina yapÄ±mÄ± +%1.", taxBonus:0, milUpkeepDiscount:2, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:-1, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:3, maxAge:16, yearsSinceUpgrade:0 },
  { id:"adv_kr_2", name:"Kefe KÃ¢tibi Canbek", role:"Liman KÃ¢tibi", stars:1, salary:12000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"+%2 Sabit Ticaret Geliri", debuff:"KÃ¢tip harcÄ± Ã§eker.", taxBonus:2, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:4, maxAge:18, yearsSinceUpgrade:0 },
  { id:"adv_kr_3", name:"Ä°zci TohtamÄ±ÅŸ", role:"Ã–ncÃ¼ Ä°zci", stars:1, salary:11000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%2 Asker SatÄ±n Alma Ä°ndirimi", debuff:"Ordu disiplini hafif dÃ¼ÅŸer.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:2, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:2, maxAge:15, yearsSinceUpgrade:0 },
  { id:"adv_kr_4", name:"Yay UstasÄ± CihanÅŸa", role:"BozkÄ±r SilahÃ§Ä±sÄ±", stars:2, salary:22000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%3 Ordu BakÄ±mÄ±", debuff:"Asker alÄ±mÄ± +%1 pahalanÄ±r.", taxBonus:0, milUpkeepDiscount:3, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:-1, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_kr_5", name:"Arslan Bey", role:"Saray SÃ¶zcÃ¼sÃ¼", stars:2, salary:25000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"+2 Mutluluk", debuff:"Ziyafet masrafÄ± Ã§eker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:6, maxAge:24, yearsSinceUpgrade:0 },
  { id:"adv_kr_6", name:"Mamay Reis", role:"Nehir KaptanÄ±", stars:2, salary:26000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%4 Donanma BakÄ±mÄ±", debuff:"Ticaret -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:4, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:7, maxAge:25, yearsSinceUpgrade:0 },
  { id:"adv_kr_7", name:"Ataman BahadÄ±r Mirza", role:"BozkÄ±r SÃ¼vari AÄŸasÄ±", stars:3, salary:45000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%5 Ordu BakÄ±mÄ± & -%4 Asker AlÄ±mÄ±", debuff:"Otlak harcÄ±rahÄ± ister.", taxBonus:0, milUpkeepDiscount:5, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:4, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:8, maxAge:26, yearsSinceUpgrade:0 },
  { id:"adv_kr_8", name:"HacÄ± Mengli Sarraf", role:"TÃ¼ccar BaÅŸÄ±", stars:3, salary:48000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"+%5 Vergi Geliri", debuff:"Komisyon keser.", taxBonus:5, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:9, maxAge:27, yearsSinceUpgrade:0 },
  { id:"adv_kr_9", name:"GÃ¶zcÃ¼ Åahin Noyan", role:"BozkÄ±r Casusu", stars:3, salary:42000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"Casusluk YanÄ±lmasÄ±nÄ± %10'a Ã§eker.", debuff:"Mektup diplomasisi -%1.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:true, ageYears:5, maxAge:23, yearsSinceUpgrade:0 },
  { id:"adv_kr_10", name:"Nogay Beyi Korkut Han", role:"Ã‡Ã¶l Kurdu", stars:4, salary:75000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%6 Ordu BakÄ±mÄ±", debuff:"Ticaret -%2.", taxBonus:-2, milUpkeepDiscount:6, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:11, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_kr_11", name:"Mimar Ä°lyas", role:"Tahkimat UstasÄ±", stars:4, salary:70000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%6 Bina YapÄ±m Ä°ndirimi", debuff:"Åantiye gideri Ã§eker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:6, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:10, maxAge:29, yearsSinceUpgrade:0 },
  { id:"adv_kr_12", name:"MÃ¼ftÃ¼ AbdÃ¼lmecid", role:"BozkÄ±r Åeyhi", stars:4, salary:65000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"+4 Mutluluk & Ä°syanÄ± %50 AzaltÄ±r", debuff:"Vergi -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:4, stopAnarchy:false, spyAccuracyBonus:false, ageYears:12, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_kr_13", name:"Han Naibi Mengli AtalÄ±k", role:"HanlÄ±k AklÄ±", stars:5, salary:130000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"+%8 Vergi Geliri & Ä°syanÄ± %0 Yapar", debuff:"Saray Ã¶deneÄŸi ister.", taxBonus:8, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:true, spyAccuracyBonus:false, ageYears:14, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_kr_14", name:"Gazi Alp Serdar", role:"Efsane AkÄ±ncÄ±", stars:5, salary:125000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"-%9 Ordu BakÄ±mÄ± & -%5 Sefer Ä°kmali", debuff:"TopÃ§u bakÄ±mÄ± +%3.", taxBonus:0, milUpkeepDiscount:9, navyUpkeepDiscount:0, artUpkeepDiscount:-3, recruitDiscount:5, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:11, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_kr_15", name:"Sarraf Karahan", role:"AltÄ±n KervancÄ±sÄ±", stars:5, salary:120000, targetName:"KÄ±rÄ±m HanlÄ±ÄŸÄ±", buff:"+%10 Vergi Geliri", debuff:"Mutluluk -2 puan.", taxBonus:10, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:13, maxAge:30, yearsSinceUpgrade:0 },

  // GÃœNEÅ DEVLETÄ° (15 Aday)
  { id:"adv_gn_1", name:"Ã‡avuÅŸ Bora", role:"Sert KollukÃ§u", stars:1, salary:10000, targetName:"GÃ¼neÅŸ Devleti", buff:"-%2 Ordu BakÄ±mÄ±", debuff:"Mutluluk -1 puan.", taxBonus:0, milUpkeepDiscount:2, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:3, maxAge:16, yearsSinceUpgrade:0 },
  { id:"adv_gn_2", name:"KÃ¶rÃ¼k UstasÄ± Kaya", role:"KÃ¼Ã§Ã¼k OcakÃ§Ä±", stars:1, salary:12000, targetName:"GÃ¼neÅŸ Devleti", buff:"-%2 TopÃ§u BakÄ±mÄ±", debuff:"Top alÄ±mÄ± +%1.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:2, recruitDiscount:-1, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:4, maxAge:17, yearsSinceUpgrade:0 },
  { id:"adv_gn_3", name:"Tellal Selim", role:"Halk KÄ±ÅŸkÄ±rtÄ±cÄ±sÄ±", stars:1, salary:11000, targetName:"GÃ¼neÅŸ Devleti", buff:"+1 Mutluluk", debuff:"Åehir asayiÅŸ masrafÄ± Ã§eker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:2, maxAge:15, yearsSinceUpgrade:0 },
  { id:"adv_gn_4", name:"Tahsildar Demir", role:"AcÄ±masÄ±z Tahsildar", stars:2, salary:24000, targetName:"GÃ¼neÅŸ Devleti", buff:"+%3 Vergi Geliri", debuff:"Mutluluk -1 puan.", taxBonus:3, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_gn_5", name:"Yaman Reis", role:"KÄ±yÄ± MuhafÄ±zÄ±", stars:2, salary:26000, targetName:"GÃ¼neÅŸ Devleti", buff:"-%3 Donanma BakÄ±mÄ±", debuff:"Gemi yapÄ±mÄ± +%2.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:3, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:-2, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:6, maxAge:24, yearsSinceUpgrade:0 },
  { id:"adv_gn_6", name:"RÃ¼kneddin Kalfa", role:"Cevher ArayÄ±cÄ±", stars:2, salary:25000, targetName:"GÃ¼neÅŸ Devleti", buff:"-%3 Bina YapÄ±m Ä°ndirimi", debuff:"Åantiye masrafÄ± Ã§eker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:3, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:23, yearsSinceUpgrade:0 },
  { id:"adv_gn_7", name:"Kara Kurt", role:"Korku MimarÄ±", stars:3, salary:48000, targetName:"GÃ¼neÅŸ Devleti", buff:"AnarÅŸistlerin zararÄ±nÄ± %30 azaltÄ±r.", debuff:"Mutluluk -2 puan.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:8, maxAge:26, yearsSinceUpgrade:0 },
  { id:"adv_gn_8", name:"Alp Erdem", role:"Disiplin SubayÄ±", stars:3, salary:52000, targetName:"GÃ¼neÅŸ Devleti", buff:"-%5 Ordu BakÄ±mÄ±", debuff:"Asker alÄ±m fiyatÄ± +%2.", taxBonus:0, milUpkeepDiscount:5, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:-2, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:9, maxAge:27, yearsSinceUpgrade:0 },
  { id:"adv_gn_9", name:"Sarraf Leon", role:"GÃ¶lge Banker", stars:3, salary:46000, targetName:"GÃ¼neÅŸ Devleti", buff:"+%5 Vergi Geliri", debuff:"Faiz kesintisi yapar.", taxBonus:5, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:7, maxAge:25, yearsSinceUpgrade:0 },
  { id:"adv_gn_10", name:"Sadrazam OÄŸuz Bey", role:"Devlet DireÄŸi", stars:4, salary:80000, targetName:"GÃ¼neÅŸ Devleti", buff:"AnarÅŸiyi %0 Yapar & +%4 Vergi", debuff:"Mutluluk -3 puan.", taxBonus:4, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-3, stopAnarchy:true, spyAccuracyBonus:false, ageYears:11, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_gn_11", name:"MÃ¼hendis Hektor", role:"Top DÃ¶kÃ¼m ÃœstadÄ±", stars:4, salary:78000, targetName:"GÃ¼neÅŸ Devleti", buff:"-%7 TopÃ§u BakÄ±mÄ±", debuff:"Top alÄ±m fiyatÄ± +%3.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:7, recruitDiscount:-3, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:10, maxAge:29, yearsSinceUpgrade:0 },
  { id:"adv_gn_12", name:"Baybars Casus BaÅŸÄ±", role:"Gizli AÄŸ UstasÄ±", stars:4, salary:72000, targetName:"GÃ¼neÅŸ Devleti", buff:"Casusluk YanÄ±lmasÄ±nÄ± %5'e Ã§eker.", debuff:"Casus maaÅŸÄ± Ã§eker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:true, ageYears:9, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_gn_13", name:"BaÅŸ Vezir NizamÃ¼ddin", role:"TiranlÄ±ÄŸÄ±n MimarÄ±", stars:5, salary:145000, targetName:"GÃ¼neÅŸ Devleti", buff:"+%8 Vergi & -%5 Bina Ä°ndirimi & Ä°syan %0", debuff:"Mutluluk -3 puan.", taxBonus:8, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:5, happinessBonus:-3, stopAnarchy:true, spyAccuracyBonus:false, ageYears:13, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_gn_14", name:"Cihangir Han MareÅŸal", role:"Yenilmez MareÅŸal", stars:5, salary:140000, targetName:"GÃ¼neÅŸ Devleti", buff:"-%8 Ordu BakÄ±mÄ± & -%6 Asker AlÄ±mÄ±", debuff:"Sefer ikramiyesi ister.", taxBonus:0, milUpkeepDiscount:8, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:6, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:12, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_gn_15", name:"Karun Mirza", role:"AltÄ±n SimyacÄ±sÄ±", stars:5, salary:130000, targetName:"GÃ¼neÅŸ Devleti", buff:"+%10 Vergi Geliri", debuff:"Mutluluk -3 puan.", taxBonus:10, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-3, stopAnarchy:false, spyAccuracyBonus:false, ageYears:14, maxAge:30, yearsSinceUpgrade:0 }
];


// ---------------- RASTGELE OLAY SÄ°STEMÄ° ----------------
const EVENT_CATEGORIES = [
 {name:"KuraklÄ±k", title:["BÃ¼yÃ¼k KuraklÄ±k","Uzayan KuraklÄ±k","AmbarlarÄ± Zorlayan KuraklÄ±k","Tarlalarda Su SÄ±kÄ±ntÄ±sÄ±","Kuruyan Nehirler"]},
 {name:"Ticaret", title:["Ticaret KervanlarÄ±","Liman Ticareti","Yeni Pazarlar","TÃ¼ccarlarÄ±n ÅikÃ¢yeti","Ticaret FÄ±rsatÄ±"]},
 {name:"Halk", title:["Halk ÅenliÄŸi","Vergi Ä°syanÄ±","Esnaf Grevi","Åehir KalabalÄ±ÄŸÄ±","HalkÄ±n Talebi"]},
 {name:"Askeri", title:["SÄ±nÄ±r Ã‡atÄ±ÅŸmasÄ±","Askeri Depo Sorunu","Hudut Garnizonu","Silah UstalarÄ±nÄ±n Talebi","Orduda Disiplin Sorunu"]},
 {name:"DoÄŸa", title:["BÃ¼yÃ¼k Sel","Åiddetli FÄ±rtÄ±na","Erken KÄ±ÅŸ","Deprem SarsÄ±ntÄ±sÄ±","Orman YangÄ±nÄ±"]},
 {name:"Diplomasi", title:["YabancÄ± ElÃ§iler","KomÅŸu Devletin Teklifi","SÄ±nÄ±r AnlaÅŸmazlÄ±ÄŸÄ±","TÃ¼ccar ElÃ§ileri","Diplomatik Kriz"]},
 {name:"Ãœretim", title:["Maden Damarlari","ZanaatkÃ¢rlarÄ±n Talebi","Yeni AtÃ¶lyeler","TahÄ±l FazlasÄ±","Ãœretim DarboÄŸazÄ±"]},
 {name:"Saray", title:["Saray MasraflarÄ±","Soylu Ailelerin Talebi","TaÃ§ TÃ¶reni","Saray Ziyafeti","Divan TartÄ±ÅŸmasÄ±"]},
 {name:"SaÄŸlÄ±k", title:["Åehirde HastalÄ±k","Hekimlerin UyarÄ±sÄ±","Åifa Evleri","Temizlik KampanyasÄ±","Karantina TartÄ±ÅŸmasÄ±"]},
 {name:"AltyapÄ±", title:["KÃ¶prÃ¼ HasarÄ±","Yol BakÄ±mÄ±","Liman OnarÄ±mÄ±","Su Kemerleri","Pazar MeydanÄ±"]},
 {name:"EÄŸitim", title:["MÃ¼derrislerin Talebi","Yeni Mektep","KÃ¼tÃ¼phane FÄ±rsatÄ±","Bilginlerin GeliÅŸi","Ã‚limlerin Ä°steÄŸi"]},
 {name:"GÃ¼venlik", title:["EÅŸkiya BaskÄ±nÄ±","Åehir GÃ¼venliÄŸi","Gece Devriyeleri","KaÃ§akÃ§Ä±lÄ±k","SÄ±nÄ±rda Haydutlar"]},
 {name:"TarÄ±m", title:["Bereketli Hasat","Ã‡iftÃ§i BorÃ§larÄ±","Tohum SÄ±kÄ±ntÄ±sÄ±","Hayvan SalgÄ±nÄ±","Yeni TarÄ±m UsulÃ¼"]},
 {name:"Maliye", title:["Hazine AÃ§Ä±ÄŸÄ±","Vergi TahsildarlarÄ±","Sikke Sorunu","BorÃ§ Talebi","Beklenmedik Gelir"]},
 {name:"Denizcilik", title:["FÄ±rtÄ±nalÄ± Sefer","Tersane Ä°htiyacÄ±","Deniz TÃ¼ccarlarÄ±","Gemi KazasÄ±","Yeni Deniz RotasÄ±"]},
 {name:"KÃ¼ltÃ¼r", title:["BÃ¼yÃ¼k Åenlik","SanatkÃ¢rlarÄ±n GeliÅŸi","Saray SanatÃ§Ä±larÄ±","AnÄ±t Talebi","Halk OyunlarÄ±"]},
 {name:"Din", title:["Manevi YardÄ±m","Ä°badethane Talebi","Din Ã‚limleri","VakÄ±f Ä°steÄŸi","Bayram HazÄ±rlÄ±klarÄ±"]},
 {name:"NÃ¼fus", title:["GÃ¶Ã§menler Geldi","Åehirden GÃ¶Ã§","Yeni Mahalle","NÃ¼fus BaskÄ±sÄ±","YerleÅŸim FÄ±rsatÄ±"]},
 {name:"Casusluk", title:["ÅÃ¼pheli Haberler","YabancÄ± Casuslar","Gizli Belgeler","Ä°stihbarat FÄ±rsatÄ±","Saraydaki FÄ±sÄ±ltÄ±lar"]},
 {name:"Ä°syan", title:["TaÅŸrada Huzursuzluk","Yerel Ä°syan","Soylu Muhalefeti","KÃ¶ylÃ¼lerin Protestosu","Åehir AyaklanmasÄ±"]}
];
const EVENT_A_TEXTS=["Kaynak ayÄ±r ve halkÄ± destekle","Hemen mÃ¼dahale et","Devlet hazinesinden Ã¶deme yap","UzlaÅŸma yolunu seÃ§","Devlet desteÄŸini artÄ±r"];
const EVENT_B_TEXTS=["MasrafÄ± reddet ve bekle","Sert tedbirler uygula","HarcamayÄ± sÄ±nÄ±rlÄ± tut","Talebi geri Ã§evir","Yerel yÃ¶neticilere bÄ±rak"];
