-- 1. GAME STATE TABLOSUNUN OLUŞTURULMASI
create table if not exists public.game_state (
  id bigint primary key,
  data jsonb not null default '{"states":[],"settings":{},"transfers":[]}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Eşzamanlı kayıt güvenliği için revision (versiyon) sütununun eklenmesi
alter table public.game_state add column if not exists revision bigint not null default 1;

-- RLS (Row Level Security) Politikaları
alter table public.game_state enable row level security;

drop policy if exists "authenticated can read game state" on public.game_state;
create policy "authenticated can read game state" on public.game_state for select to authenticated using (true);

drop policy if exists "authenticated can insert game state" on public.game_state;
create policy "authenticated can insert game state" on public.game_state for insert to authenticated with check (true);

drop policy if exists "authenticated can update game state" on public.game_state;
create policy "authenticated can update game state" on public.game_state for update to authenticated using (true) with check (true);

grant select, insert, update on public.game_state to authenticated;

-- Başlangıç verisinin eklenmesi (id = 1)
insert into public.game_state(id, data, revision) 
values (1, '{"states":[],"settings":{},"transfers":[]}'::jsonb, 1) 
on conflict(id) do nothing;


-- 2. SNAPSHOTS TABLOSUNUN OLUŞTURULMASI (Geri kazanılabilir kayıtlar)
create table if not exists public.game_state_snapshots (
  id bigint generated by default as identity primary key,
  game_state_id bigint not null references public.game_state(id) on delete cascade,
  data jsonb not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

-- Snapshot tablosu için RLS Politikaları
alter table public.game_state_snapshots enable row level security;
grant select, insert on public.game_state_snapshots to authenticated;

drop policy if exists "authenticated can read snapshots" on public.game_state_snapshots;
create policy "authenticated can read snapshots" on public.game_state_snapshots for select to authenticated using (true);

drop policy if exists "authenticated can create snapshots" on public.game_state_snapshots;
create policy "authenticated can create snapshots" on public.game_state_snapshots for insert to authenticated with check (true);


-- 3. DÜZELTİLMİŞ SAVE FUNCTION (KAYIT FONKSİYONU)
-- Eğer revision uyuşmazsa sessizce başarısız olmak yerine HATA FIRLATIR.
drop function if exists public.save_game_state(bigint, jsonb);

create or replace function public.save_game_state(expected_revision bigint, next_data jsonb)
returns table(saved_revision bigint, saved_updated_at timestamptz)
language plpgsql
set search_path = public
as $$
begin
  -- Önce güncellemeyi dene ve sonucu döndür
  return query
  update public.game_state
     set data = next_data,
         revision = revision + 1,
         updated_at = now()
   where id = 1
     and revision = expected_revision
  returning revision, updated_at;

  -- Eğer update işlemi hiçbir satırı etkilemediyse (yani expected_revision veritabanındakiyle uyuşmuyorsa)
  if not found then
    raise exception 'Eşzamanlılık hatası: Veritabanındaki oyun durumu sizinkinden daha güncel (Beklenen Revision: %)', expected_revision;
  end if;
end;
$$;

grant execute on function public.save_game_state(bigint, jsonb) to authenticated;


-- 4. REALTIME YAYINI
-- Tablonuzdaki değişiklikleri Supabase Realtime ile yayınlamak için
-- Eğer bu tablo zaten realtime'da ise PostgreSQL uyarı verebilir, uyarıyı görmezden gelebilirsiniz.
alter publication supabase_realtime add table public.game_state;
